version: "3.8"
services:
  api: 
    container_name: blogging_api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: blogging_db
      DB_USERNAME: blogging_user
      DB_PASSWORD: blogging_password
      ENVIRONMENT_NAME: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  postgres:
    image: postgres:15-alpine
    container_name: postgres_blogging
    environment:
      POSTGRES_DB: blogging_db
      POSTGRES_USER: blogging_user
      POSTGRES_PASSWORD: blogging_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blogging_user -d blogging_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: